name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    run-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      actions: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install dependencies
      run: npm Install

    - name: Run Tests
      run: npm test